<a href="https://colab.research.google.com/github/Priyanshu456574/Capstone-Project/blob/main/merge_flats_and_houses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
flats = pd.read_csv('/content/flats_cleaned.csv')
houses = pd.read_csv('/content/house_cleaned.csv')

In [ ]:
flats.head()

,property_name,property_type,society,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flats,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not_available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flats,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not_available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flats,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not_available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flats,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flats,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
df = pd.concat([flats,houses],ignore_index=True)

In [ ]:
df = df.sample(df.shape[0],ignore_index=True)

In [ ]:
df.head()

,property_name,property_type,society,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,balcony,...,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_per_sqft
0,5 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 2,7.00,NaN,5400.0,Plot area 600(501.68 sq.m.),5,6,2,...,"141, Sector 109 Gurgaon, Gurgaon, Haryana",2.0,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...","Peaceful, private, premium, gated, duplex vill...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",12963.0
1,2 BHK Flat in Sohna,flats,breez global hill view,0.35,5600.0,625.0,Carpet area: 625 (58.06 sq.m.),2,2,2,...,"Sohna, Gurgaon, Haryana",14.0,NaN,1 to 5 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...","Spacious rooms, well maintained facilities, ri...","['3 Fan', '1 Exhaust Fan', '4 Light', '1 Curta...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5...",NaN
2,2 BHK Flat in Sector-33 Sohna,flats,godrej nature plus,1.07,7725.0,1385.0,Super Built up area 1385(128.67 sq.m.),2,2,2,...,"Sector-33 Sohna, Gurgaon, Haryana",14.0,North-East,2023-08-01 00:00:00,"['Signature Global Infinity Mall Sohna', 'Bads...",We are the proud owners of this 2 bhk apartmen...,[],"['Lift(s)', 'Maintenance Staff', 'Water Storag...",NaN,NaN
3,4 BHK Flat in Sector 60 Gurgaon,flats,ireo skyon,3.60,12815.0,2809.0,Super Built up area 2809(260.96 sq.m.)Carpet a...,4,5,3,...,"Sector 60 Gurgaon, Gurgaon, Haryana",24.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...","This 4 bhk flat is located in ireo skyon, whic...","['7 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of...",NaN
4,4 BHK Flat in Sector 72 Gurgaon,flats,tata primanti,4.00,16032.0,2495.0,Super Built up area 2905(269.88 sq.m.)Carpet a...,4,5,3+,...,"2204, Sector 72 Gurgaon, Gurgaon, Haryana",22.0,West,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",This lovely 4 bhk apartment/flat in sector 72 ...,"['1 Water Purifier', '1 Exhaust Fan', '6 Geyse...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of...",NaN

In [ ]:
df.to_csv('gurgaon_properties.csv',index=False)